# Generated by Django 4.2.6 on 2023-11-24 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Continentes',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EFinal_progra_comercial.continente')),
            ],
            options={
                'db_table': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Pasaporte',
            fields=[
                ('id_pasaporte', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pasaporte', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('fecha_emision', models.DateField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EFinal_progra_comercial.pais')),
            ],
            options={
                'db_table': 'Pasaportes',
            },
        ),
    ]
